-- Esquema de la base de datos — a completar por el encargado de BD
-- Ejemplo mínimo de referencia para desbloquear al backend:

-- Tablas independientes / catálogos
CREATE TABLE EDITORIAL (
    EDITORIAL_ID CHAR(4) NOT NULL,
    NOMBRE VARCHAR(70) NOT NULL,
    PRIMARY KEY (EDITORIAL_ID)
) ENGINE=InnoDB;

CREATE TABLE CLIENTES (
    CLIENTE_ID CHAR(4) NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    APELLIDO_P VARCHAR(30) NOT NULL,
    APELLIDO_M VARCHAR(30) NULL,
    CORREO VARCHAR(50) NOT NULL UNIQUE,
    TELEFONO VARCHAR(20) NULL,
    PRIMARY KEY (CLIENTE_ID)
) ENGINE=InnoDB;

CREATE TABLE NACIONALIDAD (
    NACIONALIDAD_ID CHAR(4) NOT NULL,
    NOMBRE VARCHAR(20) NOT NULL,
    PRIMARY KEY (NACIONALIDAD_ID)
) ENGINE=InnoDB;

CREATE TABLE ESTADO_PRESTAMOS (
    ESTADO_PRESTAMOS_ID CHAR(4) NOT NULL,
    ESTADO VARCHAR(20) NOT NULL,
    PRIMARY KEY (ESTADO_PRESTAMOS_ID)
) ENGINE=InnoDB;

CREATE TABLE CARGO (
    CARGO_ID CHAR(4) NOT NULL,
    PUESTO VARCHAR(20) NOT NULL,
    PRIMARY KEY (CARGO_ID),
    CONSTRAINT CHK_Puesto CHECK (PUESTO IN ('BIBLIOTECARIO', 'ADMINISTRADOR'))
) ENGINE=InnoDB;

CREATE TABLE CATEGORIAS (
    CATEGORIA_ID CHAR(4) NOT NULL,
    NOMBRE_CATEGORIA VARCHAR(30) NOT NULL,
    PRIMARY KEY (CATEGORIA_ID)
) ENGINE=InnoDB;

-- Tablas con llaves foráneas directas
CREATE TABLE AUTORES (
    AUTOR_ID CHAR(4) NOT NULL,
    NACIONALIDAD_ID CHAR(4) NOT NULL,
    NOMBRE_AUTOR VARCHAR(50) NOT NULL,
    APELLIDO_P VARCHAR(20) NOT NULL,
    APELLIDO_M VARCHAR(20) NULL,
    PRIMARY KEY (AUTOR_ID),
    CONSTRAINT FK_AUTOR_NACIONALIDAD FOREIGN KEY (NACIONALIDAD_ID) REFERENCES NACIONALIDAD (NACIONALIDAD_ID)
) ENGINE=InnoDB;

CREATE TABLE LIBROS (
    LIBRO_ID CHAR(4) NOT NULL,
    EDITORIAL_ID CHAR(4) NOT NULL,
    TITULO VARCHAR(100) NOT NULL,
    ANIO_PUBLICACION SMALLINT NULL,
    DISPONIBLE BOOLEAN DEFAULT TRUE,
    PRIMARY KEY (LIBRO_ID),
    CONSTRAINT FK_LIBRO_EDITORIAL FOREIGN KEY (EDITORIAL_ID) REFERENCES EDITORIAL (EDITORIAL_ID)
) ENGINE=InnoDB;

CREATE TABLE USUARIOS (
    USUARIO_ID CHAR(4) NOT NULL,
    CARGO_ID CHAR(4) NOT NULL,
    USERNAME VARCHAR(20) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    NOMBRE VARCHAR(20) NOT NULL,
    APELLIDO_P VARCHAR(20) NOT NULL,
    APELLIDO_M VARCHAR(20) NULL,
    PRIMARY KEY (USUARIO_ID),
    CONSTRAINT FK_USUARIO_CARGO FOREIGN KEY (CARGO_ID) REFERENCES CARGO (CARGO_ID)
) ENGINE=InnoDB;

-- Tablas intermedias (Muchos a Muchos)
CREATE TABLE AUTORES_has_LIBROS (
    AUTOR_ID CHAR(4) NOT NULL,
    LIBRO_ID CHAR(4) NOT NULL,
    PRIMARY KEY (AUTOR_ID, LIBRO_ID),
    CONSTRAINT FK_AL_AUTOR FOREIGN KEY (AUTOR_ID) REFERENCES AUTORES (AUTOR_ID),
    CONSTRAINT FK_AL_LIBROS FOREIGN KEY (LIBRO_ID) REFERENCES LIBROS (LIBRO_ID)
) ENGINE=InnoDB;

CREATE TABLE LIBROS_has_CATEGORIAS (
    CATEGORIA_ID CHAR(4) NOT NULL,
    LIBRO_ID CHAR(4) NOT NULL,
    PRIMARY KEY (CATEGORIA_ID, LIBRO_ID),
    CONSTRAINT FK_LC_CATEGORIA FOREIGN KEY (CATEGORIA_ID) REFERENCES CATEGORIAS (CATEGORIA_ID),
    CONSTRAINT FK_LC_LIBRO FOREIGN KEY (LIBRO_ID) REFERENCES LIBROS (LIBRO_ID)
) ENGINE=InnoDB;

-- Préstamos y detalle
CREATE TABLE PRESTAMOS (
    PRESTAMO_ID CHAR(4) NOT NULL,
    ESTADO_PRESTAMOS_ID CHAR(4) NOT NULL,
    CLIENTE_ID CHAR(4) NOT NULL,
    USUARIO_ID CHAR(4) NOT NULL,
    FECHA_PRESTAMO DATE NOT NULL,
    FECHA_DEVOLUCION DATE NULL,
    PRIMARY KEY (PRESTAMO_ID),
    CONSTRAINT FK_PRESTAMO_ESTADO FOREIGN KEY (ESTADO_PRESTAMOS_ID) REFERENCES ESTADO_PRESTAMOS (ESTADO_PRESTAMOS_ID),
    CONSTRAINT FK_PRESTAMO_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTES (CLIENTE_ID),
    CONSTRAINT FK_PRESTAMO_USUARIO FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS (USUARIO_ID)
) ENGINE=InnoDB;

CREATE TABLE LIBROS_PRESTADOS (
    PRESTADOS_ID CHAR(4) NOT NULL,
    PRESTAMO_ID CHAR(4) NOT NULL,
    LIBRO_ID CHAR(4) NOT NULL,
    CANTIDAD TINYINT UNSIGNED DEFAULT 1,
    PRIMARY KEY (PRESTADOS_ID),
    CONSTRAINT FK_LP_LIBRO FOREIGN KEY (LIBRO_ID) REFERENCES LIBROS (LIBRO_ID),
    CONSTRAINT FK_LP_PRESTAMO FOREIGN KEY (PRESTAMO_ID) REFERENCES PRESTAMOS (PRESTAMO_ID)
) ENGINE=InnoDB;
